version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: jceballlos
      POSTGRES_PASSWORD: jceballos123
      POSTGRES_DB: nestdb
    ports:
      - 5432:5432